pub const SupportedFeatures = struct {
    entries: []const FeatureName = &.{},
};

pub const WGSLLanguageFeatures = struct {
    entries: []const []const u8 = &.{},
};

pub const SupportedLimits = struct {
    maxTextureDimension1D: u32 = 0,
    maxTextureDimension2D: u32 = 0,
    maxTextureDimension3D: u32 = 0,
    maxTextureArrayLayers: u32 = 0,
    maxBindGroups: u32 = 0,
    maxBindGroupsPlusVertexBuffers: u32 = 0,
    maxBindingsPerBindGroup: u32 = 0,
    maxDynamicUniformBuffersPerPipelineLayout: u32 = 0,
    maxDynamicStorageBuffersPerPipelineLayout: u32 = 0,
    maxSampledTexturesPerShaderStage: u32 = 0,
    maxSamplersPerShaderStage: u32 = 0,
    maxStorageBuffersPerShaderStage: u32 = 0,
    maxStorageBuffersInVertexStage: u32 = 0,
    maxStorageBuffersInFragmentStage: u32 = 0,
    maxStorageTexturesPerShaderStage: u32 = 0,
    maxStorageTexturesInVertexStage: u32 = 0,
    maxStorageTexturesInFragmentStage: u32 = 0,
    maxUniformBuffersPerShaderStage: u32 = 0,
    maxUniformBufferBindingSize: u64 = 0,
    maxStorageBufferBindingSize: u64 = 0,
    minUniformBufferOffsetAlignment: u32 = 0,
    minStorageBufferOffsetAlignment: u32 = 0,
    maxVertexBuffers: u32 = 0,
    maxBufferSize: u64 = 0,
    maxVertexAttributes: u32 = 0,
    maxVertexBufferArrayStride: u32 = 0,
    maxInterStageShaderVariables: u32 = 0,
    maxColorAttachments: u32 = 0,
    maxColorAttachmentBytesPerSample: u32 = 0,
    maxComputeWorkgroupStorageSize: u32 = 0,
    maxComputeInvocationsPerWorkgroup: u32 = 0,
    maxComputeWorkgroupSizeX: u32 = 0,
    maxComputeWorkgroupSizeY: u32 = 0,
    maxComputeWorkgroupSizeZ: u32 = 0,
    maxComputeWorkgroupsPerDimension: u32 = 0,
};

pub const SupportedLimitName = enum {
    maxTextureDimension1D,
    maxTextureDimension2D,
    maxTextureDimension3D,
    maxTextureArrayLayers,
    maxBindGroups,
    maxBindGroupsPlusVertexBuffers,
    maxBindingsPerBindGroup,
    maxDynamicUniformBuffersPerPipelineLayout,
    maxDynamicStorageBuffersPerPipelineLayout,
    maxSampledTexturesPerShaderStage,
    maxSamplersPerShaderStage,
    maxStorageBuffersPerShaderStage,
    maxStorageBuffersInVertexStage,
    maxStorageBuffersInFragmentStage,
    maxStorageTexturesPerShaderStage,
    maxStorageTexturesInVertexStage,
    maxStorageTexturesInFragmentStage,
    maxUniformBuffersPerShaderStage,
    maxUniformBufferBindingSize,
    maxStorageBufferBindingSize,
    minUniformBufferOffsetAlignment,
    minStorageBufferOffsetAlignment,
    maxVertexBuffers,
    maxBufferSize,
    maxVertexAttributes,
    maxVertexBufferArrayStride,
    maxInterStageShaderVariables,
    maxColorAttachments,
    maxColorAttachmentBytesPerSample,
    maxComputeWorkgroupStorageSize,
    maxComputeInvocationsPerWorkgroup,
    maxComputeWorkgroupSizeX,
    maxComputeWorkgroupSizeY,
    maxComputeWorkgroupSizeZ,
    maxComputeWorkgroupsPerDimension,
};

pub const SupportedLimitNumber = struct {
    limit: SupportedLimitName,
    amount: ?u64,
};

pub const FeatureName = enum {
    @"core-features-and-limits",
    @"depth-clip-control",
    @"depth32float-stencil8",
    @"texture-compression-bc",
    @"texture-compression-bc-sliced-3d",
    @"texture-compression-etc2",
    @"texture-compression-astc",
    @"texture-compression-astc-sliced-3d",
    @"timestamp-query",
    @"indirect-first-instance",
    @"shader-f16",
    @"rg11b10ufloat-renderable",
    @"bgra8unorm-storage",
    @"float32-filterable",
    @"float32-blendable",
    @"clip-distances",
    @"dual-source-blending",
    subgroups,
    @"texture-formats-tier1",
    @"texture-formats-tier2",
    @"primitive-index",
    @"texture-component-swizzle",
};
