pub const SupportedLimits = enum {
    maxTextureDimension1D,
    maxTextureDimension2D,
    maxTextureDimension3D,
    maxTextureArrayLayers,
    maxBindGroupsPlusVertexBuffers,
    maxBindingsPerBindGroup,
    maxDynamicUniformBuffersPerPipelineLayout,
    maxDynamicStorageBuffersPerPipelineLayout,
    maxSampledTexturesPerShaderStage,
    maxSamplersPerShaderStage,
    maxStorageBuffersPerShaderStage,
    maxStorageBuffersInVertexStage,
    maxStorageBuffersInFragmentStage,
    maxStorageTexturesPerShaderStage,
    maxStorageTexturesInVertexStage,
    maxStorageTexturesInFragmentStage,
    maxUniformBuffersPerShaderStage,
    maxUniformBufferBindingSize,
    maxStorageBufferBindingSize,
    minUniformBufferOffsetAlignment,
    minStorageBufferOffsetAlignment,
    maxVertexBuffers,
    maxBufferSize,
    maxVertexAttributes,
    maxVertexBufferArrayStride,
    maxInterStageShaderVariables,
    maxColorAttachments,
    maxColorAttachmentBytesPerSample,
    maxComputeWorkgroupStorageSize,
    maxComputeInvocationsPerWorkgroup,
    maxComputeWorkgroupSizeX,
    maxComputeWorkgroupSizeY,
    maxComputeWorkgroupSizeZ,
    maxComputeWorkgroupsPerDimension,
};

pub const SupportedLimitNumber = struct {
    limit: SupportedLimits,
    amount: ?u64,
};

pub const FeatureName = enum {
    @"core-features-and-limits",
    @"depth-clip-control",
    @"depth32float-stencil8",
    @"texture-compression-bc",
    @"texture-compression-bc-sliced-3d",
    @"texture-compression-etc2",
    @"texture-compression-astc",
    @"texture-compression-astc-sliced-3d",
    @"timestamp-query",
    @"indirect-first-instance",
    @"shader-f16",
    @"rg11b10ufloat-renderable",
    @"bgra8unorm-storage",
    @"float32-filterable",
    @"float32-blendable",
    @"clip-distances",
    @"dual-source-blending",
    subgroups,
    @"texture-formats-tier1",
    @"texture-formats-tier2",
    @"primitive-index",
    @"texture-component-swizzle",
};
